language: c
dist: xenial
cache: ccache
services:
  - docker

env:
  global:
    - ARCH=powerpc

matrix:
  include:
    - os:   linux-ppc64le
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-19.04 DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le (native) (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux-ppc64le
      env:  TARGET=kernel SUBARCH=ppc64le IMAGE=ubuntu-devel DEFCONFIG=ppc64le_defconfig
      name: "kernel: ppc64le GCC9 (native) (PPC_BOOK3S_64 && LITTLE_ENDIAN)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=ppc64_defconfig
      name: "kernel: ppc64 (PPC_BOOK3S_64 && BIG_ENDIAN)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=corenet64_smp_defconfig
      name: "kernel: corenet64_smp (PPC_BOOK3E_64)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=pmac32_defconfig
      name: "kernel: pmac32 (PPC_BOOK3S_32)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=ppc40x_defconfig
      name: "kernel: ppc40x (PPC_40x)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=ppc44x_defconfig
      name: "kernel: ppc44x (PPC_44x)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=mpc885_ads_defconfig
      name: "kernel: mpc885_ads (PPC_8xx)"
    - os:   linux
      env:  TARGET=kernel SUBARCH=ppc64 IMAGE=ubuntu-19.04 DEFCONFIG=corenet32_smp_defconfig
      name: "kernel: corenet32_smp (PPC_85xx)"
    - os:   linux-ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-19.04
      name: "ppctests: ppc64le (native) Ubuntu 19.04"
    - os:   linux-ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-18.10
      name: "ppctests: ppc64le (native) Ubuntu 18.10"
    - os:   linux-ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-18.04
      name: "ppctests: ppc64le (native) Ubuntu 18.04"
    - os:   linux-ppc64le
      env:  TARGET=ppctests SUBARCH=ppc64le IMAGE=ubuntu-16.04
      name: "ppctests: ppc64le (native) Ubuntu 16.04"
    - os:   linux
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-19.04
      name: "ppctests: ppc64 Ubuntu 19.04"
    - os:   linux
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-18.10
      name: "ppctests: ppc64 Ubuntu 18.10"
    - os:   linux
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-18.04
      name: "ppctests: ppc64 Ubuntu 18.04"
    - os:   linux
      env:  TARGET=ppctests SUBARCH=ppc64 IMAGE=ubuntu-16.04
      name: "ppctests: ppc64 Ubuntu 16.04"
    - os:   linux-ppc64le
      env:  TARGET=selftests SUBARCH=ppc64le IMAGE=ubuntu-19.04
      name: "selftests: ppc64le (native)"
    - os:   linux
      env:  TARGET=selftests SUBARCH=ppc64 IMAGE=ubuntu-19.04
      name: "selftests: ppc64 (native)"

install:
  - docker pull linuxppc/build:$IMAGE-$(uname -m)

script:
  - travis_wait 50 ./arch/powerpc/tools/ci-build.sh
